### ISSUE TITLE
Character database update notification is persistent.

### ISSUE THREAD

**Issue by gbmall** [BambusControl/obsidian-unicode-search#15]
Every time I launch obsidian, I get a notification like in the attached image.

<img width="1848" height="674" alt="Image" src="https://github.com/user-attachments/assets/9b7f1f2a-a744-4f48-a967-c00fb45f8b1a" />

**Comment by MG240** [comment]
I'm facing the same issue. Also, the notification appears even when navigating in and out of the plugin settings page without making any changes.

**Comment by victagon** [comment]
Same here, hopefully you can find the time at some point to disable the message.

**Comment by BambusControl** [comment]
Hello, this smells of a bug.
The message should only show once, when the database update occurs.
What platform (mac/android/pc etc) are you guys using?

**Comment by MG240** [comment]
I'm using Windows. The notification message appears every time I launch Obsidian and whenever I navigate away from the plugin's settings page, even without making any changes.

```
SYSTEM INFO:
	Obsidian version: v1.9.12
	Installer version: v1.9.12
	Operating system: Windows 11 Pro 10.0.26100
	Login status: not logged in
	Language: en
	Insider build toggle: off
	Live preview: on
	Base theme: adapt to system
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 2
	Plugins enabled: 1
		1: Unicode Search v0.7.1

RECOMMENDATIONS:
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

```

**Comment by gbmall** [comment]
I am using MacOS and iPadOS.

**Comment by BambusControl** [comment]
Hm, the versions seem to be all good, so perhaps there is an issue with the save data itself.
However, I cannot seem to replicate it myself.

Could you please send me the `data.json` file from the `.obsidian/plugins/unicode-search` directory?
It'll help me see what save data state makes creates the bug.

**Comment by gbmall** [comment]
[data.json](https://github.com/user-attachments/files/22197360/data.json)

**Comment by victagon** [comment]
[data.json](https://github.com/user-attachments/files/22229783/data.json)

Btw: running latest Obsidian (1.9.12) on Linux Mint (22.2)

**Comment by BambusControl** [comment]
Fixed in [0.7.2](https://github.com/BambusControl/obsidian-unicode-search/releases/tag/0.7.2)

**Comment by MG240** [comment]
The issue still seems to be present in `0.7.2`.

[data.json](https://github.com/user-attachments/files/22421207/data.json)

```
SYSTEM INFO:
	Obsidian version: v1.9.12
	Installer version: v1.9.12
	Operating system: Windows 11 Pro 10.0.26100
	Login status: not logged in
	Language: en
	Insider build toggle: off
	Live preview: on
	Base theme: adapt to system
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 1
	Plugins enabled: 1
		1: Unicode Search v0.7.2

RECOMMENDATIONS:
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

```

**Comment by gbmall** [comment]
Oh, no!

For me, it is gone. MacOS and iPadOS.

> The issue still seems to be present in `0.7.2`.

**Comment by BambusControl** [comment]
Thanks @MG240, I think I finally fixed the issue.

Unicode characters are weird because they are multi-character strings in JS, so now I unbounded the length of any Unicode character representation.
The Unicode character `שּׁ` in your save file threw an error, because it is 3-characters long.

**Comment by MG240** [comment]
@BambusControl Thanks a lot. Much appreciated!
